language: python
sudo: false

before_deploy:
  - cd /home/travis/build/chriswbartley/monoensemble

deploy:
  provider: pypi
  user: chriswbartley
  password:
    secure: nsCWqwrRjH8tLsip2cOAzvq+B8cX1kn3RrTnIJ4Y5JkUOaM8l8QhNzMw84xLOFEr+ZO2RRGaj+p9JBYiyMALHd9ovoh6tICzUACAYAE7Wy8Tjx7ZdMrkKpvtO/Twh7tzvtb7XRQDPR/ucgv+LFrrFt+/7YzFfadkIlETMPw0n9B692gFYVcbkvlwX84i9o7Cf7h9cKCia+WI6aG9F+x54tDZXXQzsKXdAo93Od4+eniDIi6fOx0NQsUxpRAK4UqPs96SfHVS4mkWUq1HotqXH7UrgsiwZRkTnFmPzNo0eKfQTI/S/2ZYwvNji8Cl6VNWQjns3ccCJ7zmp3DcDOftvdH2N0xj5FL600SqF2oumXKj9oqBEKO55ED+XxJrPgBP81/eURbJh1IQFGRLhNGGrdUE/wCCMPtni953oNH17thhQGqZprc9T6qCZs2wrTJ7FkhwFb0V205drI42Q8pB6qCo5uzoVXfYWbinusmKU6Uo87WZaefr1DfexjGPh174CIIoo6PWDWIOZ0c5Bvdu4HI8+D+ic2s3bRgX/rBKgpOT568ZMsTeFpg3DD3ywVvrz8IUwXf2wnVSO0QStWxKI8nI5uTXVTwGWd6zaccDUMxiZrdduWqwI4IxCuY2IAxj2qVWXgR/rwJrDBYE0JpO7YkLhWn+eNxi0LaFmfRwb/c=
  on:
    tags: true
    repo: chriswbartley/monoensemble
  skip_cleanup: true

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8 cython"

python:
  - '3.6'


install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806,E128 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/` --exclude *example*.*
- mkdir for_test_
- cd for_test_
- py.test --pyargs monoensemble --cov-report term-missing --cov=monoensemble

after_success:
- coveralls
- cd..
- dir
